### ISSUE TITLE
Reconfiguration of MSF CNF with FSM

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-industrial-pilot#257]
Once triggered, the FSM belonging to the MSF (MDC, Suricata, Filebeat) CNF should restart the CNF and set a new value for the `MQTT_BROKER_HOST` env var.

Will require adjusting the code of the FSM here: https://github.com/sonata-nfv/tng-industrial-pilot/blob/master/fsms/mdc-fsm/mdc/mdcfsm.py#L149

Belongs to use case 2: https://github.com/sonata-nfv/tng-industrial-pilot/issues/31

**Comment by stefanbschneider** [comment]
Simply need to return a dict of the format

```
---
status: 'COMPLETED'
envs:
  - cdu_id: <id of first cdu>
    envs:
      foo: bar
      spam: ni
  - cdu_id: <id of second cdu>
      envs:
        bar: foo
```
